language: php
php:
  - 7.1
  - 7.2
  - 7.3
cache:
  directories:
    - $HOME/.composer/cache
install:
  - composer install
script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
